databases:
  - name: railsseven
    databaseName: railsseven
    user: railsseven

services:
  - type: web
    name: railsseven
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railsseven
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
